#!/bin/sh

app="janetdocs"
working_tree="/home/sean/$app"
port="9002"

while read oldrev newrev ref
do
    echo "Master ref received.  Deploying master branch to production..."

    echo "Shutting down server..."
    pkill -f '$app'

    echo "Cloning new files"
    git --work-tree=$working_tree --git-dir=/home/sean/$app.git checkout -f
    cd $working_tree

    echo "Migrating database"
    DATABASE_URL=/home/sean/$app/$app-production.sqlite3 joy migrate

    # echo "Running jpm deps"
    # jpm deps

    echo "Starting server..."
    bash -c "exec -a $app janet main.janet $port &> app.log &"

    echo "   /==============================="
    echo "   | DEPLOYMENT COMPLETED"
    echo "   | Target branch: master"
    echo "   | Target folder: $working_tree"
    echo "   \=============================="

done

exit 0